

<h1 class='h1'>Frequently Asked Questions</h1>
<h3 ><span class="s2"><b>HOW DO I GET CARE IF I'VE BEEN INJURED AND I HAVE NO INSURANCE?</b></span><span class="s1"><br>
</span><span class="s2">If you have been injured in an motor vehicle accident through no fault of your own and you do not have insurance, or you cannot afford your deductibles or copays, you may be able to receive medical treatment through a medical lien or your own auto insurance. <b>It is important for you to see a doctor as soon as possible, even if you do not have an attorney.</b> You want to be sure you will have access to a wide range of treatment options and board certified medical specialists. The scope of treatment options and quality of care available to you is directly dependent on the relationships established between the attorney that handles your case and the medical professionals providing your care. </span></h3>
<h3 ><span class="s2"><b>I CAN'T FIND A PHYSICIAN IN THE FORT WORTH AREA THAT WILL SEE MOTOR VEHICLE ACCIDENTS, EVEN WITH INSURANCE</b></span><span class="s1"><br>
</span><span class="s2">This is actually the norm, not the exception. Many doctors do not want to risk having to testify about your injuries. If you have insurance and a liability situation exists, many insurance companies will argue about whose responsibility it is to pay your medical bills and some may even have exclusions from their contracts with physicians. Payments may be delayed or not paid at all as one side claims the other is responsible. If you do not have insurance, very few doctors will accept a medical lien.</span><span class="s1"><br>
</span><span class="s2">Unfortunately, this often gives patients little option but to go to an emergency room. While doctors in the ER can rule out life or limb threatening injuries, they are not set up for definitive treatment and rehabilitation. Patients are discharged with a limited supply of medication and instructed to see a doctor in clinic, but are frequently unable to find one.</span></h3>
<h3 ><span class="s2"><b>MY PRIMARY CARE DOCTOR WILL NOT SEE ME FOR A MOTOR VEHICLE ACCIDENT</b></span><span class="s1"><br>
</span><span class="s2">This is very common for reasons above. Your PCP can refer you to PIC for an evaluation, or you can call directly for an appointment. PIC does not require a doctor’s referral.</span></h3>
<h3 ><span class="s2"><b>I DO NOT HAVE AN ATTORNEY YET, SHOULD I WAIT TO SEE A DOCTOR</b></span><span class="s1"><br>
</span><span class="s2">No, any injuries you have from a car or truck accident should be diagnosed as soon as possible and treatment begun.</span></h3>
<h3 ><span class="s2"><b>MY CAR WAS TOTALED OR IS NOT DRIVABLE AND THE AT-FAULT DRIVERS INSURANCE IS DELAYING PROVIDING A RENTAL CAR, SHOULD I WAIT TO SEE A DOCTOR UNTIL I GET TRANSPORTATION? </b></span><span class="s1"><br>
</span><span class="s2">No, it is important to see a physician and get established as a patient as soon as possible if you have been injured in a motor vehicle accident. Rent a car yourself, use a car service, or get a friend to take you but see a physician as soon as possible. Some insurance companies will delay your rental and try to use that against you later as “delay in treatment” of your injuries.</span></h3>
<h3 ><span class="s2"><b>THE OTHER DRIVER WAS AT FAULT AND THEIR AUTO INSURANCE COMPANY FIXED MY CAR, BUT THEY WILL NOT PAY ANY OF MY MEDICAL BILLS</b></span><span class="s1"><br>
</span><span class="s2">Unfortunately, this is the norm as well. It is hard to understand but you can expect very little assistance or payment for your injuries from the at-fault driver’s insurance carrier. They will often fix your car, give you a rental, and even replace your car seat but will give no assistance to treating your injuries.</span></h3>
<h3 ><span class="s2"><b>WHAT IF I NEED SURGERY?</b></span><span class="s1"><br>
</span><span class="s2">Fortunately, 80-90% of musculoskeletal injuries do not require surgery. Our independent physicians have a wide variety of treatments to get you better without surgery if at all possible. If these treatments fail, or if you have a problem that is only correctible by surgery, you will be referred to one of our network surgeons. Your primary treating doctor will review the case with the respective surgeon before you go to assure you are seeing the right surgeon for the right problem at the right time. </span></h3>
<h3 ><span class="s2"><b>I LIVE OUT OF TOWN. DO YOU SEE PATIENTS OUT OF TOWN?</b></span><span class="s1"><br>
</span><span class="s2">If you reside out of the Fort Worth area and do not have access to the types of services provided by Physician Injury Consultants, we may be able to help. It is possible travel and lodging can be arranged to allow you to have the treatment you need. We treat many patients from out of town and even some from out of state.<b><i>&nbsp;Email us today</i></b> for more information and to review your specific situation.</span></h3>
