<h1 class='h1 text-center' >Frequently Asked Questions</h1>
<div class='space-y-8 max-w-[990px] mx-auto px-3'>
  <h3><span class="s2"><b>How do I get care if I've been injured and have no insurance?</b></span><span class="s1"><br></span><span class="s2">If you've been injured in a motor vehicle accident that wasn't your fault and you don't have insurance, or if you can't afford deductibles or copays, you may still be able to receive medical treatment through a medical lien or your auto insurance. <b><i>It's crucial to see a doctor as soon as possible, even if you don't have an attorney.</i></b> This ensures you have access to a wide range of treatment options and board-certified medical specialists. The quality and scope of care you receive directly depends on the relationships between your attorney and the medical professionals handling your case.</span></h3>

<h3><span class="s2"><b>I can't find a physician in the Fort Worth area who treats motor vehicle accident injuries, even with insurance</b></span><span class="s1"><br></span><span class="s2">Unfortunately, this is more common than you'd expect. Many doctors are hesitant to treat motor vehicle accident injuries due to the possibility of having to testify in court. Even if you have insurance, liability disputes can arise, with insurance companies arguing over who is responsible for paying your medical bills. In some cases, payments may be delayed or denied. Without insurance, finding a doctor willing to accept a medical lien can be even more difficult.</span><span class="s1"><br></span><span class="s2">As a result, many patients feel they have no choice but to visit the emergency room. While ER doctors can rule out life- or limb-threatening injuries, they are not equipped for ongoing treatment and rehabilitation. Patients are often discharged with a short-term supply of medication and advised to follow up with a clinic doctor, but finding one can be challenging.</span></h3>
  
<h3><span class="s2"><b>My primary care doctor won't see me for a motor vehicle accident</b></span><span class="s1"><br></span><span class="s2">This is a common issue for the reasons mentioned above. Your primary care physician (PCP) can refer you to Astra Injury Rehabilitation Consultants for an evaluation, or you can contact us directly to schedule an appointment. Astra Injury Rehabilitation Consultants does not require a doctor’s referral.</span></h3>
  
<h3><span class="s2"><b>I don't have an attorney yet—should I wait to see a doctor?</b></span><span class="s1"><br></span><span class="s2">No, you should not wait. It's important to have any injuries from a car or truck accident diagnosed and treated as soon as possible.</span></h3>
  
<h3><span class="s2"><b>My car isn't drivable, and the at-fault driver's insurance is delaying providing a rental car. Should I wait to see a doctor until I have transportation?</b></span><span class="s1"><br></span><span class="s2">No, it's important to see a doctor and get established as a patient as soon as possible after a motor vehicle accident. If needed, rent a car, use a car service, or ask a friend for a ride, but don't delay seeing a physician. Some insurance companies might try to use any delay in treatment against you later.</span></h3>
  
<h3><span class="s2"><b>The other driver was at fault, and their insurance fixed my car, but they won't pay my medical bills</b></span><span class="s1"><br></span><span class="s2">Unfortunately, this is common. While it may be hard to understand, you can often expect minimal assistance with your medical expenses from the at-fault driver’s insurance carrier. They may cover the cost of fixing your car, provide a rental, and even replace your car seat, but they often refuse to cover your medical treatment.</span></h3>
  
<h3><span class="s2"><b>What if I need surgery?</b></span><span class="s1"><br></span><span class="s2">Fortunately, 80–90% of musculoskeletal injuries do not require surgery. Our independent physicians offer a wide range of treatments aimed at helping you recover without surgery whenever possible. If these treatments are not effective, or if surgery is the only option, you'll be referred to one of our network surgeons. Your primary treating doctor will review your case with the surgeon to ensure you see the right specialist at the right time.</span></h3>
  
<h3><span class="s2"><b>I live out of town. Do you treat patients who are out of town?</b></span><span class="s1"><br></span><span class="s2">If you live outside the Fort Worth area and don't have access to services like those offered by Astra Injury Rehabilitation Consultants, we may still be able to assist you. Travel and lodging arrangements can often be made so that you can receive the treatment you need. We regularly treat out-of-town and even out-of-state patients. <b><i>Email us today</i></b> for more information and to discuss your specific situation.</span></h3>
</div>
<div id='spacer' class =''>
</div>